spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1071200186213-51hadcbfk6s5kr0q9d6balg7n6o291a3.apps.googleusercontent.com
            clientSecret: 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
            scope: openid, profile, email, https://www.googleapis.com/auth/youtube

logging:
  level:
    com.example: DEBUG
    com.springframework.security: TRACE
    com.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE